networks:
  federal:

name: federal-use-cases
services:
  dot-orderer-1:
    container_name: dot-orderer-1
    environment:
      - FABRIC_LOGGING_SPEC=DEBUG
      - ORDERER_GENERAL_BOOTSTRAPMETHOD=none
    image: hyperledger/fabric-orderer:3.1.1
    networks:
      - federal
    ports:
      - "7050:7050"
      - "8443:8443"
    volumes:
      - ./federal/hosts/dot-orderer-1/etc:/etc/hyperledger/fabric
      - ./federal/hosts/dot-orderer-1/var:/var/hyperledger
      - ./federal/cryptography/certs/ordererOrganizations/orderer.transportation.gov/users/Admin@orderer.transportation.gov/tls:/var/hyperledger/orderer/admin
      - ./federal/cryptography/certs/ordererOrganizations/orderer.transportation.gov/orderers/dot-orderer-1.orderer.transportation.gov/msp:/var/hyperledger/orderer/msp
      - ./federal/cryptography/certs/ordererOrganizations/orderer.transportation.gov/orderers/dot-orderer-1.orderer.transportation.gov/tls:/var/hyperledger/orderer/tls
      # ATTENTION! YOU MUST CHANGE THE BIN PATH TO EITHER THE X64 OR ARM DIRECTORY BASED ON YOUR COMPUTER'S ARCHITECTURE
      - ./bin/linux/X64/osnadmin:/usr/local/bin/osnadmin

  nhtsa-peer-0:
    build:
      context: .
      dockerfile: Peer_Dockerfile
    container_name: nhtsa-peer0
    depends_on:
      - dot-orderer-1
    environment:
      - ADMIN_MSP=/etc/hyperledger/fabric/admin/msp
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/fabric/admin/msp
      - CORE_PEER_TLS_ENABLED=true
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=federal-use-cases_federal
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - PEER_MSP=/etc/hyperledger/fabric/msp
      - PEER_ADDRESS=nhtsa-peer-0
      - PEER_PORT=7051
      - PEER_MSP=NHTSAMSP
    networks:
      - federal
    ports:
      - "7051:7051"
      - "7052:7052"
    volumes:
      - ../code/firmware_updates/FirmwareUpdates/build/install:/chaincode
      - ../code/fmvss_certification/FmvssCertification/build/install:/chaincode
      - ../code/recall_notifications/RecallNotifications/build/install:/chaincode
      - ../code/vehicle_state/VehicleState/build/install:/chaincode
      - ./federal/cryptography/certs/ordererOrganizations/orderer.transportation.gov/orderers/dot-orderer-1.orderer.transportation.gov/tls:/var/hyperledger/orderer/tls
      - ./federal/cryptography/certs/peerOrganizations/nhtsa.gov/peers/peer0.nhtsa.gov:/etc/hyperledger/fabric
      - ./federal/cryptography/certs/peerOrganizations/nhtsa.gov/users/Admin@nhtsa.gov:/etc/hyperledger/fabric/admin
      - ./federal/hosts/nhtsa-peer0/etc/core.yaml:/etc/hyperledger/fabric/core.yaml
      - ./federal/hosts/nhtsa-peer0/hyperledger:/var/hyperledger/production
      # Docker socket -- on Mac you MUST enable the default builder
      - /var/run/docker.sock:/host/var/run/docker.sock
      # ATTENTION! YOU MUST CHANGE THE BIN PATH TO EITHER THE X64 OR ARM DIRECTORY BASED ON YOUR COMPUTER'S ARCHITECTURE
      - ./bin/linux/X64/configtxlator:/usr/local/bin/configtxlator
      - ./bin/linux/X64/discover:/usr/local/bin/discover
