test:
  workers:
    number: 4
  rounds:
#    - label: "Create Recall List for Vehicle and View Recall List for Vehicle - 5 TPS"
#      txNumber: 10000
#      rateControl:
#        type: fixed-rate
#        opts:
#          tps: 5
#      workload:
#        module: federal/hosts/caliper/recall/public/benchmarks/vehicle-list-test.js
#        arguments:
#          contractId: recall-notifications-chaincode
#          filePath: federal/hosts/caliper/recall/public/data/public-recall-vehicle-list
#    - label: "Create Recall List for Vehicle and View Recall List for Vehicle - 10 TPS"
#      txNumber: 10000
#      rateControl:
#        type: fixed-rate
#        opts:
#          tps: 10
#      workload:
#        module: federal/hosts/caliper/recall/public/benchmarks/vehicle-list-test.js
#        arguments:
#          contractId: recall-notifications-chaincode
#          filePath: federal/hosts/caliper/recall/public/data/public-recall-vehicle-list
#    - label: "Create Recall List for Vehicle and View Recall List for Vehicle - 15 TPS"
#      txNumber: 10000
#      rateControl:
#        type: fixed-rate
#        opts:
#          tps: 15
#      workload:
#        module: federal/hosts/caliper/recall/public/benchmarks/vehicle-list-test.js
#        arguments:
#          contractId: recall-notifications-chaincode
#          filePath: federal/hosts/caliper/recall/public/data/public-recall-vehicle-list
#    - label: "Create Recall List for Vehicle and View Recall List for Vehicle - 20 TPS"
#      txNumber: 10000
#      rateControl:
#        type: fixed-rate
#        opts:
#          tps: 20
#      workload:
#        module: federal/hosts/caliper/recall/public/benchmarks/vehicle-list-test.js
#        arguments:
#          contractId: recall-notifications-chaincode
#          filePath: federal/hosts/caliper/recall/public/data/public-recall-vehicle-list
    - label: "Create Recall and View Recall for Vehicle - 5 TPS"
      txNumber: 10000
      rateControl:
        type: fixed-rate
        opts:
          tps: 5
      workload:
        module: federal/hosts/caliper/recall/public/benchmarks/recall-test.js
        arguments:
          contractId: recall-notifications-chaincode
          filePath: federal/hosts/caliper/recall/public/data/public-recall
    - label: "Create Recall and View Recall for Vehicle - 10 TPS"
      txNumber: 10000
      rateControl:
        type: fixed-rate
        opts:
          tps: 10
      workload:
        module: federal/hosts/caliper/recall/public/benchmarks/recall-test.js
        arguments:
          contractId: recall-notifications-chaincode
          filePath: federal/hosts/caliper/recall/public/data/public-recall
    - label: "Create Recall and View Recall for Vehicle - 15 TPS"
      txNumber: 10000
      rateControl:
        type: fixed-rate
        opts:
          tps: 15
      workload:
        module: federal/hosts/caliper/recall/public/benchmarks/recall-test.js
        arguments:
          contractId: recall-notifications-chaincode
          filePath: federal/hosts/caliper/recall/public/data/public-recall
    - label: "Create Recall and View Recall for Vehicle - 20 TPS"
      txNumber: 10000
      rateControl:
        type: fixed-rate
        opts:
          tps: 20
      workload:
        module: federal/hosts/caliper/recall/public/benchmarks/recall-test.js
        arguments:
          contractId: recall-notifications-chaincode
          filePath: federal/hosts/caliper/recall/public/data/public-recall