test:
  workers:
    number: 4
  rounds:
    - label: "Issue and View License - 4 TPS"
      txNumber: 10000
      rateControl:
        type: fixed-rate
        opts:
          tps: 4
      workload:
        module: state/hosts/caliper/licensing/state/benchmarks/issue-license-test.js
        arguments:
          contractId: licensing-chaincode
          filePath: state/hosts/caliper/licensing/state/data/licensing
    - label: "Issue and View License - 8 TPS"
      txNumber: 10000
      rateControl:
        type: fixed-rate
        opts:
          tps: 8
      workload:
        module: state/hosts/caliper/licensing/state/benchmarks/issue-license-test.js
        arguments:
          contractId: licensing-chaincode
          filePath: state/hosts/caliper/licensing/state/data/licensing
    - label: "Issue and View License - 12 TPS"
      txNumber: 10000
      rateControl:
        type: fixed-rate
        opts:
          tps: 12
      workload:
        module: state/hosts/caliper/licensing/state/benchmarks/issue-license-test.js
        arguments:
          contractId: licensing-chaincode
          filePath: state/hosts/caliper/licensing/state/data/licensing
    - label: "Issue and View License - 16 TPS"
      txNumber: 10000
      rateControl:
        type: fixed-rate
        opts:
          tps: 16
      workload:
        module: state/hosts/caliper/licensing/state/benchmarks/issue-license-test.js
        arguments:
          contractId: licensing-chaincode
          filePath: state/hosts/caliper/licensing/state/data/licensing

    - label: "Issue and Revoke License - 4 TPS"
      txNumber: 10000
      rateControl:
        type: fixed-rate
        opts:
          tps: 4
      workload:
        module: state/hosts/caliper/licensing/state/benchmarks/revoke-license-test.js
        arguments:
          contractId: licensing-chaincode
          filePath: state/hosts/caliper/licensing/state/data/licensing
    - label: "Issue and Revoke License - 8 TPS"
      txNumber: 10000
      rateControl:
        type: fixed-rate
        opts:
          tps: 8
      workload:
        module: state/hosts/caliper/licensing/state/benchmarks/revoke-license-test.js
        arguments:
          contractId: licensing-chaincode
          filePath: state/hosts/caliper/licensing/state/data/licensing
    - label: "Issue and Revoke License - 12 TPS"
      txNumber: 10000
      rateControl:
        type: fixed-rate
        opts:
          tps: 12
      workload:
        module: state/hosts/caliper/licensing/state/benchmarks/revoke-license-test.js
        arguments:
          contractId: licensing-chaincode
          filePath: state/hosts/caliper/licensing/state/data/licensing
    - label: "Issue and Revoke License - 16 TPS"
      txNumber: 10000
      rateControl:
        type: fixed-rate
        opts:
          tps: 16
      workload:
        module: state/hosts/caliper/licensing/state/benchmarks/revoke-license-test.js
        arguments:
          contractId: licensing-chaincode
          filePath: state/hosts/caliper/licensing/state/data/licensing
